import argparse
import sys


def read_file(text_file):
    line_str = ""
    with open(text_file) as r:
        for line in r:
            line_str += line
    return line_str

# TODO: Need to find a way to read in tables.

parser = argparse.ArgumentParser()
parser.add_argument('report_data', help = "The report data generated by 'XX_report_writer'")
parser.add_argument('template_tex', help = "The template tex file to be editing")
parser.add_argument('output_tex', help = "The tex file that is going to be written to")
parser.add_argument('-t', '--Table', help = "Optional Table.txt file for reports that include tables")

try:
    args = parser.parse_args()
except SystemExit:
    print("No input recognised. Please try again")
    sys.exit()

args = parser.parse_args()

report_data_file = args.report_data
template_file = args.template_tex
output_file = args.output_tex
table_data = ""
if args.Table:
    table_file = args.Table
    table_data = read_file(table_file)

report_data = read_file(report_data_file)

replace_list = report_data.split('\n')

out_str = ""
with open(template_file, 'rt') as report_tex:
    l = 0
    for line in report_tex:
        for i in range(0, len(replace_list)):
            lookFor = str(replace_list[i]).split(' : ')[0]
            replaceWith = str(replace_list[i]).split(' : ')[1]
            if lookFor in line:
                print("%s in line %s" % (lookFor, l))
                line = line.replace(lookFor, replaceWith)
            if "TABLEHERE" in line:
                print("Table added at line %s" % l)
                line = line.replace("TABLEHERE", table_data)
        out_str += line
        l += 1

with open(output_file, 'wt') as w:
    w.write(out_str)
